"""empty message

Revision ID: d4fc4e6da0f6
Revises: 
Create Date: 2021-01-13 16:30:30.759698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4fc4e6da0f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_name', sa.String(length=80), nullable=True),
    sa.Column('playlist_filename', sa.String(length=255), nullable=True),
    sa.Column('avatar_s', sa.String(length=64), nullable=True),
    sa.Column('avatar_m', sa.String(length=64), nullable=True),
    sa.Column('avatar_l', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_playlist_name'), 'playlist', ['playlist_name'], unique=True)
    op.create_table('track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album', sa.String(length=120), nullable=True),
    sa.Column('albumartist', sa.String(length=80), nullable=True),
    sa.Column('artist', sa.String(length=80), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=140), nullable=True),
    sa.Column('composer', sa.String(length=80), nullable=True),
    sa.Column('disc', sa.Integer(), nullable=True),
    sa.Column('disc_total', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('filesize', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=20), nullable=True),
    sa.Column('samplerate', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('tracknum', sa.String(length=3), nullable=True),
    sa.Column('track_total', sa.String(length=3), nullable=True),
    sa.Column('year', sa.String(length=8), nullable=True),
    sa.Column('url', sa.String(length=240), nullable=True),
    sa.Column('artist_title', sa.String(length=80), nullable=True),
    sa.Column('filename', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_artist_title'), 'track', ['artist_title'], unique=True)
    op.create_index(op.f('ix_track_filename'), 'track', ['filename'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('playlist__memberships',
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.PrimaryKeyConstraint('playlist_id', 'track_id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_table('playlist__memberships')
    op.drop_table('followers')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_track_filename'), table_name='track')
    op.drop_index(op.f('ix_track_artist_title'), table_name='track')
    op.drop_table('track')
    op.drop_index(op.f('ix_playlist_playlist_name'), table_name='playlist')
    op.drop_table('playlist')
    # ### end Alembic commands ###
